CREATE DATABASE DE1_XEMAY
GO 
USE DE1_XEMAY
GO
CREATE TABLE XeMay(
	MaXe INT IDENTITY NOT NULL PRIMARY KEY,
	TenXe VARCHAR(30) NULL,
	MoTa NVARCHAR(50) NULL,
	GiaNhap FLOAT NULL,
	SoLuong INT NULL,
	MaLoaiXe INT NULL
) 
GO 
CREATE TABLE LoaiXM(
	MaLoaiXe INT IDENTITY NOT NULL,
	TenLoaiXe VARCHAR(30) NULL,
	
)
GO
INSERT INTO XeMay
VALUES('SH', '150i', 120000000, 12, 1),
	('Vespa', '175cc', 11000000, 5, 2)
GO
INSERT INTO LoaiXM
VALUES (N'Hạng sang'),
		(N'Hạng thường')
GO